require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/filials", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Filial. As you add validations to Filial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Filial.create! valid_attributes
      get filials_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      filial = Filial.create! valid_attributes
      get filial_url(filial)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_filial_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      filial = Filial.create! valid_attributes
      get edit_filial_url(filial)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Filial" do
        expect {
          post filials_url, params: { filial: valid_attributes }
        }.to change(Filial, :count).by(1)
      end

      it "redirects to the created filial" do
        post filials_url, params: { filial: valid_attributes }
        expect(response).to redirect_to(filial_url(Filial.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Filial" do
        expect {
          post filials_url, params: { filial: invalid_attributes }
        }.to change(Filial, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post filials_url, params: { filial: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested filial" do
        filial = Filial.create! valid_attributes
        patch filial_url(filial), params: { filial: new_attributes }
        filial.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the filial" do
        filial = Filial.create! valid_attributes
        patch filial_url(filial), params: { filial: new_attributes }
        filial.reload
        expect(response).to redirect_to(filial_url(filial))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        filial = Filial.create! valid_attributes
        patch filial_url(filial), params: { filial: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested filial" do
      filial = Filial.create! valid_attributes
      expect {
        delete filial_url(filial)
      }.to change(Filial, :count).by(-1)
    end

    it "redirects to the filials list" do
      filial = Filial.create! valid_attributes
      delete filial_url(filial)
      expect(response).to redirect_to(filials_url)
    end
  end
end
