require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/marriages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Marriage. As you add validations to Marriage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Marriage.create! valid_attributes
      get marriages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      marriage = Marriage.create! valid_attributes
      get marriage_url(marriage)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_marriage_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      marriage = Marriage.create! valid_attributes
      get edit_marriage_url(marriage)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Marriage" do
        expect {
          post marriages_url, params: { marriage: valid_attributes }
        }.to change(Marriage, :count).by(1)
      end

      it "redirects to the created marriage" do
        post marriages_url, params: { marriage: valid_attributes }
        expect(response).to redirect_to(marriage_url(Marriage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Marriage" do
        expect {
          post marriages_url, params: { marriage: invalid_attributes }
        }.to change(Marriage, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post marriages_url, params: { marriage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested marriage" do
        marriage = Marriage.create! valid_attributes
        patch marriage_url(marriage), params: { marriage: new_attributes }
        marriage.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the marriage" do
        marriage = Marriage.create! valid_attributes
        patch marriage_url(marriage), params: { marriage: new_attributes }
        marriage.reload
        expect(response).to redirect_to(marriage_url(marriage))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        marriage = Marriage.create! valid_attributes
        patch marriage_url(marriage), params: { marriage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested marriage" do
      marriage = Marriage.create! valid_attributes
      expect {
        delete marriage_url(marriage)
      }.to change(Marriage, :count).by(-1)
    end

    it "redirects to the marriages list" do
      marriage = Marriage.create! valid_attributes
      delete marriage_url(marriage)
      expect(response).to redirect_to(marriages_url)
    end
  end
end
